sudo: required
services:
  - docker

before_install:
  - docker build -t xbumasa/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xbumasa/udemy-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "udemy-docker-react"
  env: "UdemyDockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-638825234179"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
