sudo: required
services:
  - docker

before_install:
  - docker build -t xbumasa/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xbumasa/udemy-docker-react npm run test -- --coverage
